### PR TITLE
Sublibs

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by douwefokkema** [comment]
I merged the above. But now I am getting compile errors. On : cmake -A Win32 -G "Visual Studio 17 2022" -DCMAKE_GENERATOR_PLATFORM=Win32 ..
I get the following:
C:\radar\AutoTrackRaymarine_pi\build [sublibs +22 ~1 -0 !]> cmake -A Win32 -G "Visual Studio 17 2022" -DCMAKE_GENERATOR_PLATFORM=Win32 ..
-- CMakeLists: USE_GL: ON
-- CMakeLists: Build type: Release
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
-- PluginSetup: GIT_REPOSITORY_SERVER not found setting to: github.com
-- PluginSetup: PROJECT_VERSION: 1.18.26.0
-- PluginSetup: AutoTrackRaymarine Version: 1.18.26.0
-- PluginSetup: OPCN_FLATPAK:
-- PluginSetup: OCPN_FLATPAK_CONFIG: , OCPN_FLATPAK_BUILD: , UNIX:
-- PluginSetup: WX_VER:
-- PluginSetup: PKG_TARGET_WX_VER: -wx, WX_VER:
-- PluginSetup: ARCH: x86_64
-- PluginSetup: PKG_TARGET: msvc, PKG_TARGET_VERSION: 10.0.19045
-- PluginSetup: OCPN_TARGET:
-- PluginSetup: PKG_TARGET: msvc
-- PluginSetup: CMAKE version: 3.26.1
-- PluginConfigure: *** Staging to build AutoTrackRaymarine_pi ***
-- PluginConfigure: CIRCLECI: , Env CIRCLECI:
-- PluginConfigure: TRAVIS: , Env TRAVIS:
-- PluginConfigure: Branch is not tracking a remote branch
-- PluginConfigure: GIT_REPOSITORY:
-- PluginConfigure: Git Branch: "sublibs"
-- PluginConfigure: Git Tag: ""
-- PluginConfigure: GIT_BRANCH_OR_TAG: branch
-- PluginConfigure: GIT_REPOSITORY_ITEM: sublibs
-- PluginConfigure: CLOUDSMITH_BASE_REPOSITORY: autotrackraymarine
-- PluginConfigure: PLUGIN_EXTRA_VERSION_VARS: Not Found
-- PluginConfigure: PLUGIN_EXTRA_FORMBUILDER_HEADERS: PLUGIN_EXTRA_FORMBUILDER_HEADERS-NOTFOUND
-- PluginConfigure: PLUGIN_EXTRA_FORMBUILDER_HEADERS: Not found
-- PluginConfigure: ENV BUILD_GTK3:
-- PluginConfigure: BUILD_ENV: , BUILD_ENV_TEMP , OCPN_TARGET:
-- PluginConfigure: Doing build_gtk3:
-- PluginConfigure: PKG_TARGET_GTK:
-- PluginConfigure: ARCH: x86_64
-- PluginConfigure: PKG_NVR: AutoTrackRaymarine_pi-1.18.26.0, PKG_TARGET: msvc, ARCH: x86_64, PKG_TARGET_WX_VER: -wx, PKG_BUILD_GTK: , PKG_TARGET_VERSION: 10.0.19045, OCPN_TARGET:
-- PluginConfigure: PACKAGING_NAME: AutoTrackRaymarine_pi-1.18.26.0-msvc-x86_64-10.0.19045
-- PluginConfigure: PACKAGING_NAME_XML: AutoTrackRaymarine_pi-1.18.26.0-msvc-x86_64-10.0.19045
-- PluginConfigure: PKG_TARGET_FULL: msvc-wx
-- PluginConfigure: PKG_BUILD_TARGET: msvc
-- PluginConfigure: PKG_BUILD_GTK:
-- PluginConfigure: PKG_BUILT_WITH_GTK:
-- PluginConfigure: *.in files generated in C:/radar/AutoTrackRaymarine_pi/build
-- PluginConfigure: Set SNPRINTF
-- PluginConfigure: Finding package OpenGL
-- PluginConfigure:     Adding local GLU
CMake Error at cmake/PluginConfigure.cmake:496 (add_subdirectory):
  add_subdirectory given source "opencpn-libs/glu" which is not an existing
  directory.
Call Stack (most recent call first):
  CMakeLists.txt:135 (include)


-- PluginConfigure: PACKAGE_NAME: AutoTrackRaymarine_pi
-- PluginConfigure:     Revised GL Lib (with local): opengl32glu32
-- PluginConfigure: wxWidgets_Version:
-- PluginConfigure: wxWidgets components: base;core;net;xml;html;adv;aui
-- PluginConfigure: Found wxWidgets...
-- PluginConfigure:  wxWidgets Include: C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/mswu;C:/OpenCPN/cache/wxWidgets-3.2.2/include
-- PluginConfigure:  wxWidgets Libraries: debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32ud.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32u.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32ud_core.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32u_core.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32ud_net.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32u_net.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32ud_xml.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32u_xml.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32ud_html.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32u_html.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32ud_adv.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32u_adv.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32ud_aui.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32u_aui.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxpngd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxpng.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxtiffd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxtiff.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxjpegd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxjpeg.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxzlibd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxzlib.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxregexud.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxregexu.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxexpatd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxexpat.lib;winmm;comctl32;uuid;oleacc;uxtheme;rpcrt4;shlwapi;version;wsock32
-- PluginConfigure:  Revised wxWidgets Libraries: debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32ud.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32u.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32ud_core.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32u_core.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32ud_net.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32u_net.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32ud_xml.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxbase32u_xml.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32ud_html.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32u_html.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32ud_adv.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32u_adv.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32ud_aui.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxmsw32u_aui.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxpngd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxpng.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxtiffd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxtiff.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxjpegd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxjpeg.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxzlibd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxzlib.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxregexud.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxregexu.lib;debug;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxexpatd.lib;optimized;C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/wxexpat.lib;winmm;comctl32;uuid;oleacc;uxtheme;rpcrt4;shlwapi;version;wsock32
CMake Warning (dev) at CMakeLists.txt:190 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "AutoTrackRaymarine_pi" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CMakeLists: Adding target link libraries to AutoTrackRaymarine_pi
-- Using bundled tinyxml
CMake Error at CMakeLists.txt:208 (add_subdirectory):
  add_subdirectory given source "opencpn-libs/jsonlib" which is not an
  existing directory.


-- PluginInstall: *** Will install to C:/Program Files (x86)/AutoTrackRaymarine  ***
-- PluginInstall: Install Prefix: C:/Program Files (x86)/AutoTrackRaymarine
-- PluginInstall: Install Data: plugins\\AutoTrackRaymarine_pi
-- PluginLocalization: Starting POTFILE generation
-- PluginLocalization: Checking file: C:/radar/AutoTrackRaymarine_pi/po/AutoTrackRaymarine_pi.pot
-- PluginLocalization: Found: C:/radar/AutoTrackRaymarine_pi/po/AutoTrackRaymarine_pi.pot
-- PluginLocalization: Creating Resources directory
-- PluginPackage: Package: OCPN_FLATPAK_CONFIG:
-- PluginPackage: CPACK_PACKAGE_NAME:
-- PluginPackage: CPACK_PACKAGE_VERSION 1.18.26.0-ov58
-- PluginPackage: FILE: AutoTrackRaymarine_pi_1.18.26.0-ov58-ov58_win32
-- PluginPackage: Stripping debug information from module
CMake Warning (dev) in cmake/PluginPackage.cmake:
  A logical block opening on the line

    C:/radar/AutoTrackRaymarine_pi/cmake/PluginPackage.cmake:118 (if)

  closes on the line

    C:/radar/AutoTrackRaymarine_pi/cmake/PluginPackage.cmake:144 (endif)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:243 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- PluginPackage: CPACK_PACKAGE_FILE_NAME: AutoTrackRaymarine_pi-1.18.26.0-msvc-x86_64-10.0.19045
-- PluginPackage: FILE: AutoTrackRaymarine_pi-1.18.26.0-msvc-x86_64-10.0.19045
-- PluginPackage: CPACK_PACKAGE_VERSION: 1.18.26.0-ov58, PACKAGE_VERSION 1.18.26.0, CPACK_PACKAGE_FILE_NAME: AutoTrackRaymarine_pi-1.18.26.0-msvc-x86_64-10.0.19045
-- PluginPackage: PROJECT_SOURCE_DIR: C:/radar/AutoTrackRaymarine_pi, CPACK_PROJECT_CONFIG_FILE: C:/radar/AutoTrackRaymarine_pi/build/PluginCPackOptions.cmake
-- CMakeLists: include directories:
-- CMakeLists: dir='C:/radar/AutoTrackRaymarine_pi/build/CMakeFiles/include'
-- CMakeLists: dir='C:/radar/AutoTrackRaymarine_pi/include'
-- CMakeLists: dir='C:/radar/AutoTrackRaymarine_pi/src'
-- CMakeLists: dir='C:/OpenCPN/cache/wxWidgets-3.2.2/lib/vc14x_dll/mswu'
-- CMakeLists: dir='C:/OpenCPN/cache/wxWidgets-3.2.2/include'
-- Configuring incomplete, errors occurred!

**Comment by rgleason** [comment]
```
CMake Error at cmake/PluginConfigure.cmake:496 (add_subdirectory):
add_subdirectory given source "opencpn-libs/glu" which is not an existing
directory.
Call Stack (most recent call first):
CMakeLists.txt:135 (include)
```

This is a little new to me. I haven't done a PR and merge before.   
Maybe the local opencpn-libs needs to be refreshed. 

Please refer to Dave's instructions and my comments here
https://github.com/jongough/testplugin_pi/issues/332

I think if you have the opencpn-libs folder showing locally, (and I don't know if the whole 77mb downloaded)!!
So first check to see what the size of it is.  If it is too small, then we have to do something with the opencpn-libs.

First try,

Build Locally

```
For your local builds, after doing:

 Delete opencpn-libs,and then issue:
$ git submodule update --init opencpn-libs
$ git submodule update --remote --merge opencpn-libs
Commit and push the results.
This command pulls in all the latest updates to the opencpn-libs module.
This will fix all builds except flatpak.

This is exactly what the CI process does. It will bring in a fresh copy of opencpn-libs from github.
It does not change the git repo contents at all, since you already have the git reference to opencpn-libs.

You generally need to only do this once (for each plugin), unless opencpn-libs is changed by me or Alec.
We will let you know if that happens.

Remember: treat opencpn-libs as a read-only library. Do not edit. Do not commit contents.

Dave

```

Let me know if this worked please. So I know what others have to do.

**Comment by rgleason** [comment]
Douwe, see this more complete note I left for Jon

https://github.com/jongough/testplugin_pi/pull/337

**Comment by douwefokkema** [comment]
Right, updating opencpn-libs did the trick. I can compile locally again. What next, merge to master?

**Comment by rgleason** [comment]
Douwe, 
Have you done this already as part of API118?  In particular the  getpluginversionpatch and post stuff?
https://github.com/jongough/testplugin_pi/issues/339

Next step is going to be to use the new version of opencpn-libs that Dave and Alec have been working on.
I would just work out of the sublibs branch for a little while longer, or using your browser go to your github repos and make a Pu;ll request to your master branch from your sublibs branch.  Be very careful about the direction of the PR and also remember to push all changes up from local to your sublibs repos.

The both master and sublibs are identical, and you can make the changes to update/change opencpn-libs in sublibs branch, push that up and when that is working ok make a PR from sublibs to your master branch again.

Just an idea.

**Pull request merged**
